name: Antares CI (monorepo)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  JWT_SECRET: ${{ secrets.JWT_SECRET || 'dummy-secret-for-ci' }}
  # Option flags (override in repo secrets if you want)
  BUILD_IMAGES: 'false'   # set 'true' to build images in CI
  PUSH_IMAGES: 'false'    # set 'true' + configure DOCKER_REGISTRY secrets to push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l -o pipefail

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # --- Frontend (Node) ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/antares-app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install frontend deps
        working-directory: ./antares-app
        run: npm ci

      - name: Build frontend
        working-directory: ./antares-app
        run: npm run build -- --configuration production

      # --- Backend (Maven) ---
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/antares-api/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & test backend
        working-directory: ./antares-api
        env:
          SPRING_APPLICATION_JSON: '{"application.security.jwt.cookie.secure": false}'
          JWT_SECRET: ${{ env.JWT_SECRET }}
        run: |
          chmod +x ./mvnw
          ./mvnw -B verify

      # --- Optional: build docker images ---
      - name: Build docker images
        if: env.BUILD_IMAGES == 'true'
        run: |
          docker build -t antares-api:ci ./antares-api
          docker build -t antares-app-nginx:ci ./antares-app

      # --- Optional: push images to registry ---
      - name: Push docker images
        if: env.PUSH_IMAGES == 'true'
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login $DOCKER_REGISTRY -u "${DOCKER_USERNAME}" --password-stdin
          docker tag antares-api:ci ${DOCKER_REGISTRY}/antares-api:ci
          docker tag antares-app-nginx:ci ${DOCKER_REGISTRY}/antares-app-nginx:ci
          docker push ${DOCKER_REGISTRY}/antares-api:ci
          docker push ${DOCKER_REGISTRY}/antares-app-nginx:ci
